# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 077e06869d3d66c0b0fff90a40213736286dc3367d1527bd9b6060ebcea8c21a22555c16b1e39a5edb2cc167a3ffdee5945240702ce2b54fd032861c7ee7d6d0

test:
  secret_key_base: 9908d53c08786d4aa3975d498f685404be06c91e6be87fb1206b718a98e5e1edfd38995ee9d86a033cdbed11fdec759724332fd3f6469e62bbabb74998634936

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
